In [ ]:
import numpy as np
a=np.array([[1,2,3,4,5],[11,12,13,14,15],[21,22,23,24,25]])
a[1,2:4]

array([13, 14])

In [ ]:
import numpy as np
a=np.array([[1,2,3,4,5],[11,12,13,14,15],[21,22,23,24,25]])
a[:,2]

array([ 3, 13, 23])

In [ ]:
import numpy as np
a=np.array([[1,2,3,4,5],[11,12,13,14,15],[21,22,23,24,25]])
a.sum(axis=0)

array([33, 36, 39, 42, 45])

In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([[4,5,6]])
a+b

array([[5, 7, 9]])

In [ ]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [ ]:
x @ y

32

In [ ]:
x * y

array([ 4, 10, 18])

In [ ]:
np.dot(x,y)

32

In [ ]:
np.sum(x*y)

32

In [ ]:
import numpy as np

w = np.zeros(5)
w = w + 2
print(w)

[2. 2. 2. 2. 2.]


In [ ]:
import numpy as np
a = np.linspace(-1,1,5)
b = a * 2 + 4
print(b)

[2. 3. 4. 5. 6.]


In [ ]:
import numpy as np
a = [[1,2,3],[4,5,6]]
b = [[7,8],[9,10],[11,12]]
print(np.dot(a,b))

[[ 58  64]
 [139 154]]


In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8],[9,10],[11,12]])
print(a @ b)

[[ 58  64]
 [139 154]]


In [ ]:
import numpy as np
a = np.array([[1,2],[1,3],[1,5]])
x = np.array([1,2])
b = np.array([3,4,5])
print(a@x-b)

[2 3 6]


In [ ]:
import numpy as np
M = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
b = np.array([1, 2, 3, 4])
print (M + b)

[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]]


In [ ]:
import numpy as np
M = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
b = np.array([1, 2, 3])
b = np.expand_dims(b, axis = 1)
# print(b)
print (M + b)

[[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]]


In [ ]:
import numpy as np
def mean(X):
    """
    Compute the mean of the columns of X

    Argument:
    	X: np.ndarray
    Return:
    	mean_X: np.ndarray
    """
    m = np.mean(X, axis=0)
    return m
X = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
print (mean(X))

[5. 6. 7. 8.]
